# Copyright (c) 2021 Jesse N. <jesse@keplerdev.com>
# This work is licensed under the terms of the MIT license. For a copy, see <https://opensource.org/licenses/MIT>.

version: "3.8"

services:
  sqlserver01:
    container_name: sqlserver01
    image: jessenich91/mssql-server:latest
    restart: unless-stopped
    stop_grace_period: 1m30s
    network_mode: bridge
    env_file:
      - sqlserver.env
      - sqlserver.secrets.env
    ports:
      - "1443:1433"
      - "1444:1434"
    volumes:
      - sqldata:/var/opt/mssql
      # - "sqldbsystem:/var/opt/mssql"
      # - "sqldbdata:/var/opt/mssql/data"
      # - "sqldblog:/var/opt/mssql/log"
      # - "sqldbbackup:/var/opt/mssql/backup"

  sqlpad:
    container_name: sqlpad
    image: sqlpad/sqlpad:latest
    restart: unless-stopped
    stop_grace_period: 1m30s
    network_mode: bridge
    ports:
      - "3001:3000"
    env_file:
      - sqlpad.env
      - sqlpad.secrets.env
    volumes:
      - sqlpad:/var/lib/sqlpad

volumes:
  # sqldbsystem:
  # sqldbdata:
  # sqldblog:
  # sqldbbackup:
  sqlpad:
  sqldata:
