# Copyright (c) 2021 Jesse N. <jesse@keplerdev.com>
# This work is licensed under the terms of the MIT license. For a copy, see <https://opensource.org/licenses/MIT>.

version: "3.8"

services:
  sqlserver01:
    image: jessenich91/mssql-server:latest
    restart: unless-stopped
    stop_grace_period: 1m30s
    network_mode: bridge
    env_file:
      - sqlserver.env
      - sqlserver.secrets.env
    build:
      dockerfile: Dockerfile
      context: .
      args:
        VARIANT: 2019-latest
      labels:
        maintainer: Jesse N. <jesse@keplerdev.com>
        com.keplerdev.maintainer: Jesse N. <jesse@keplerdev.com>
        com.keplerdev.image.base: "mcr.microsoft.com/mssql/server:2019-latest"
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: 3
    ports:
      - "1433:1433/tcp"
      - "1434:1434/udp"
    volumes:
      - "sqldbsystem:/var/opt/mssql"
      - "sqldbdata:/var/opt/mssql/data"
      - "sqldblog:/var/opt/mssql/log"
      - "sqldbbackup:/var/opt/mssql/backup"

  sqlpad:
    image: sqlpad/sqlpad:latest
    hostname: 'sqlpad'
    ports:
      - '3010:3000'
    env_file:
      - sqlpad.env
      - sqlpad.secrets.env
    volumes:
      - sqlpad:/var/lib/sqlpad

volumes:
  sqldbsystem:
  sqldbdata:
  sqldblog:
  sqldbbackup:
  sqlpad:
