# Copyright (c) 2021 Jesse N. <jesse@keplerdev.com>
# This work is licensed under the terms of the MIT license. For a copy, see <https://opensource.org/licenses/MIT>.

name: "Publish Docker Image"

on:
  push:
    tags:
      - "v*"
      - "*-prerelease-*"
      - "*-rc-*"

env:
  DOCKERHUB_LIBRARY: jessenich91
  DOCKERHUB_REPO: mssql-server
  GHCR_URI: ghcr.io


jobs:
  build-docker-image:
    runs-on: "ubuntu-latest"
    env:
      LABELS: |
        "maintainer: Jesse N. <jesse@keplerdev.com>"
        "com.keplerdev.maintainer: Jesse N. <jesse@keplerdev.com>"
        "com.keplerdev.source-sha": ${{ github.sha }}
        "com.keplerdev.registry.github: ${{ env.GHCR_URI }}/${{ github.actor }}/${{ env.DOCKERHUB_REPO }}"
        "com.keplerdev.repository.github: https://github.com/${{ github.repository }}"
        "com.keplerdev.registry.dockerhub: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}""
        "com.keplerdev.repository.dockerhub: https://dockerhub.com/r/${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}"

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
          driver-opts: image=moby/buildkit:master
          use: true

      - name: Buildx Builder Create
        run: |
          docker buildx create --platform linux/amd64,linux/arm64/v8,linux/arm/v7 --use

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR_URI }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            "${{ env.DOCKERHUB_LIBRARY }}/${{ env.DOCKERHUB_REPO }}"
            "${{ env.GHCR_URI }}/${{ github.actor }}/${{ env.DOCKERHUB_REPO }}"
          tags: type=semver,pattern={{version}}

      - name: Build & Push 2019 Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          labels: ${{ env.LABELS }}
          build-args: |
            VARIANT=latest
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          pull: true
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
