# Copyright (c) 2021 Jesse N. <jesse@keplerdev.com>
# This work is licensed under the terms of the MIT license. For a copy, see <https://opensource.org/licenses/MIT>.

name: "Publish Docker Image"

on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"
      - "*-prerelease-*"
      - "*-rc-*"

env:
  DOCKERHUB_LIBRARY: jessenich91
  DOCKERHUB_REPO: mssql-server
  GHCR_URI: ghcr.io


jobs:
  build-docker-image:
    runs-on: "ubuntu-latest"
    env:
      LABELS: |
        "maintainer: Jesse N. <jesse@keplerdev.com>"
        "com.keplerdev.metadata.maintainer: Jesse N. <jesse@keplerdev.com>"
        "com.keplerdev.metadata.source.sha: ${{ github.sha }}"
        "com.keplerdev.metadata.source.ref: ${{ github.ref }}"
        "com.keplerdev.metadata.build.run-id: ${{ github.run_id }}"
        "com.keplerdev.metadata.build.run-number: ${{ github.run_number }}"
        "com.keplerdev.metadata.builder.workflow.name: ${{ github.workflow }}"

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
          driver-opts: image=moby/buildkit:master
          use: true

      - name: Buildx Builder Create
        run: |
          docker buildx create --platform linux/amd64,linux/arm64/v8,linux/arm/v7 --use

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR_URI }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            "${{ env.DOCKERHUB_LIBRARY }}/${{ env.DOCKERHUB_REPO }}"
            "${{ env.GHCR_URI }}/${{ github.actor }}/${{ env.DOCKERHUB_REPO }}"
          tags: |
            type=semver,enable=${{ startsWith(github.ref, 'refs/tags/') }},pattern={{major}}.{{minor}}.{{patch}}
            type=semver,enable=${{ startsWith(github.ref, 'refs/tags/') }},pattern={{major}}.{{minor}}
            type=semver,enable=${{ startsWith(github.ref, 'refs/tags/') }},pattern={{major}}
            type=edge,enable=${{ !startsWith(github.ref, 'refs/tags/') }},priority=700,prefix={{branch}}-,suffix=-latest,branch=$repo.default_branch
            type=edge,enable=${{ !startsWith(github.ref, 'refs/tags/') }},priority=700,prefix={{branch}}-,suffix=-{{sha}},branch=$repo.default_branch
          flavor: latest=auto
          labels: ${{ env.LABELS }}

      - name: Build & Push 2019 Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          labels: "${{ steps.meta.outputs.labels }}"
          build-args: |
            VARIANT=2019-latest
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          pull: true
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
